# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Photo',
        ),
    ]
