# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=60)),
                ('no', models.CharField(max_length=10)),
            ],
        ),
    ]
