# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
