# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_identity_number'),
        ('users', '0004_address_user'),
    ]

    operations = [
    ]
