# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20170530_0212'),
        ('users', '0005_merge_20170529_2258'),
    ]

    operations = [
    ]
