# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 02:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 5, 11, 2, 23, 9, 207444, tzinfo=utc))),
                ('account_type', models.CharField(max_length=50)),
                ('currency_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
