# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 3, 56, 51, 888048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Currency'),
        ),
    ]
