# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 8, 33, 51, 589307, tzinfo=utc)),
        ),
    ]
