# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
