# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170511_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 5, 16, 43, 214022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='currency_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Currency'),
        ),
    ]
