# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loan_loanaccountpayment_transaction'),
        ('accounts', '0002_auto_20170525_1133'),
    ]

    operations = [
    ]
