# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 05:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170511_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 5, 18, 49, 796944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
