# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170529_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
