# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_transaction_is_done'),
        ('accounts', '0005_auto_20170529_1421'),
    ]

    operations = [
    ]
