# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20170529_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('BİRİKİM HESABI', 'BİRİKİM HESABI'), ('KREDİLİ MEVDUAT HESABI', 'KREDİLİ MEVDUAT HESABI'), ('NORMAL HESAP', 'NORMAL HESAP'), ('EMEKLİLİK HESABI', 'EMEKLİLİK HESABI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sending_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
