# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170530_1532'),
        ('accounts', '0008_auto_20170530_1901'),
    ]

    operations = [
    ]
